# theme: jekyll-theme-minimal
name: Miss Refrain
site_incorp: 2023
title: Professional Dominatrix
strap: She doesn't refrain from instilling pain
site_path: https://missrefrain.github.io/
include: ['_pagecontent', '_booking']
services:
  - Rope bondage
  - Corporal punishment
  - Lock chastity
  - Foot worship
  - Sissification
  - Submissive dress up
  - Role play
  - Gender transform
  - Weigh and measure
  - Fetish modelling
  - Phone sex
  - Masked camming
hour_rate:
  - 150
findom_service:
  - FinDom  
findom_price:
  - 650
debt_contract_service:
  - Debt contract
debt_contract_price:
  - 650
location_intimates_service:
  - Location intimates
location_intimates_price:
  - 70
mail_order_intimates_service:
  - Mail Order intimates  
mail_order_intimates_price:
  - 40
disclaimer:
  - Engaging in BDSM activities, including the giving and receiving of pain, should always be based on mutual consent, trust, and respect. It is recommended to educate oneself about safe practices, proper techniques, and risk mitigation to ensure a positive and enjoyable experience for all involved parties.
relative_permalinks: false
