# theme: jekyll-theme-minimal
name: Miss Refrain
title: Professional Dominatrix
strap: She doesn't refrain from instilling pain
site_path: https://missrefrain.github.io/
# include: ['_projects']
services:
	item1: Rope bondage
	item2: Diaper discipline
	item3: Corporal punishment
	item4: Key holding/chastity
	item5: Foot worship
	item6: Sissy-fication
	item7: Submissive dress up
	item8: Role play
	item9: Gender transformation
	item10: Location ‘intimates’exchange
	item11: Mail order ‘intimates’ exchange
	item12: Weigh & Measure the Dominatrix
	item13: Gold star Orgasm
FinDom*
	item14: Debt contract by date*
	item15: Masked fetish modelling
	item16: Phone sex
	item17: Masked camming
relative_permalinks: false
