# theme: jekyll-theme-minimal
name: Miss Refrain
title: Professional Dominatrix
strap: She doesn't refrain from instilling pain
site_path: https://missrefrain.github.io/
# include: ['_projects']
relative_permalinks: false
service:
 service1: Rope bondage
 service2: Diaper discipline
 service3: Corporal punishment
 service4: Key holding/chastity
 service5: Foot worship
 service6: Sissy-fication
 service7: Submissive dress up
 service8: Role play
 service9: Gender transformation
 service10: Location ‘intimates’exchange
 service11: Mail order ‘intimates’ exchange
 service12: Weigh & Measure the Dominatrix
 service13: Gold star Orgasm
FinDom*
 service14: Debt contract by date*
 service15: Masked fetish modelling
 service16: Phone sex
 service17: Masked camming