# theme: jekyll-theme-minimal
name: Miss Refrain
title: Professional Dominatrix
strap: She doesn't refrain from instilling pain
site_path: https://missrefrain.github.io/
include: ['_booking']
services:
  - Rope bondage
  - Diaper discipline
  - Corporal punishment
  - Lock chastity
  - Foot worship
  - Sissy-fication
  - Submissive dress up
  - Role play
  - Gender transform
  - Location intimates
  - Location intimates
  - Weigh & measure
  - Gold star orgasm
  - FinDom
  - Debt contract
  - Fetish modelling
  - Phone sex
  - Masked camming
hour_rate:
  - 150
findom_price:
  - 650
debt_contract_price:
  - 650
location_intimates_price:
  - 70
mail_order_intimates_price:
  - 40
relative_permalinks: false
