# theme: jekyll-theme-minimal
name: Miss Refrain
title: Professional Dominatrix
strap: She doesn't refrain from instilling pain
site_path: https://missrefrain.github.io/
# include: ['_projects']
relative_permalinks: false
