# theme: jekyll-theme-minimal
name: Miss Refrain
title: Professional Dominatrix
strap: She doesn't refrain from instilling pain
site_path: https://missrefrain.github.io/
include: ['_pagecontent', '_booking']
services:
  - Rope bondage
  - Corporal punishment
  - Lock chastity
  - Foot worship
  - Sissification
  - Submissive dress up
  - Role play
  - Gender transform
  - Weigh and measure
  - Gold star orgasm
  - Fetish modelling
  - Phone sex
  - Masked camming
hour_rate:
  - 150
findom_service:
  - FinDom  
findom_price:
  - 650
debt_contract_service:
  - Debt contract
debt_contract_price:
  - 650
location_intimates_service:
  - Location intimates
location_intimates_price:
  - 70
mail_order_intimates_service:
  - Mail Order intimates  
mail_order_intimates_price:
  - 40
relative_permalinks: false
