# theme: jekyll-theme-minimal
name: Miss Refrain
title: Professional Dominatrix
strap: She doesn't refrain from instilling pain
site_path: https://missrefrain.github.io/
# include: ['_projects']
relative_permalinks: false
service_one: Rope bondage
service_two: Diaper discipline
service_three: Corporal punishment
service_four: Key holding/chastity
service_five: Foot worship
service_six: Sissy-fication
service_seven: Submissive dress up
service_eight: Role play
service_nine: Gender transformation
service_ten: Location ‘intimates’exchange
service_eleven: Mail order ‘intimates’ exchange
service_twelve: Weigh & Measure the Dominatrix
service_thirteen: Gold star Orgasm
FinDom*
service_fourteen: Debt contract by date*
service_fifteen: Masked fetish modelling
service_sixteen: Phone sex
service_seventeen: Masked camming