# theme: jekyll-theme-minimal
name: Miss Refrain
title: Professional Dominatrix
strap: She doesn't refrain from instilling pain
site_path: https://missrefrain.github.io/
# include: ['_projects']
services:
 - Rope bondage @ £150.00 p/h
 - Diaper discipline
 - Corporal punishment
 - Key holding/chastity
 - Foot worship
 - Sissy-fication
 - Submissive dress up
 - Role play
 - Gender transformation
 - Location ‘intimates’ exchange
 - Mail order ‘intimates’ exchange
 - Weigh & Measure the Dominatrix
 - Gold star Orgasm
 - FinDom*
 - Debt contract by date*
 - Masked fetish modelling
 - Phone sex
 - Masked camming
relative_permalinks: false
