# theme: jekyll-theme-minimal
name: Miss Refrain
title: Professional Dominatrix
strap: She doesn't refrain from instilling pain
site_path: https://missrefrain.github.io/
# include: ['_projects']
relative_permalinks: false
service_01: Rope bondage
service_02: Diaper discipline
service_03: Corporal punishment
service_04: Key holding/chastity
service_05: Foot worship
service_06: Sissy-fication
service_07: Submissive dress up
service_08: Role play
service_09: Gender transformation
service_10: Location ‘intimates’exchange
service_11: Mail order ‘intimates’ exchange
service_12: Weigh & Measure the Dominatrix
service_13: Gold star Orgasm
FinDom*
service_14: Debt contract by date*
service_15: Masked fetish modelling
service_16: Phone sex
service_17: Masked camming