# theme: jekyll-theme-minimal
name: Miss Refrain
title: Professional Dominatrix
strap: She doesn't refrain from instilling pain
site_path: https://missrefrain.github.io/
# include: ['_projects']
services:
 - Rope bondage @ £150.00 p/h
 - Diaper discipline @ £150.00 p/h
 - Corporal punishment @ £150.00 p/h
 - Key holding/chastity @ £150.00 p/h
 - Foot worship @ £150.00 p/h
 - Sissy-fication @ £150.00 p/h
 - Submissive dress up @ £150.00 p/h
 - Role play @ £150.00 p/h
 - Gender transformation @ £150.00 p/h
 - Location ‘intimates’ exchange @ £150.00 p/h
 - Mail order ‘intimates’ exchange @ £150.00 p/h
 - Weigh & Measure the Dominatrix @ £150.00 p/h
 - Gold star orgasm @ £150.00 p/h
 - FinDom + price set by Miss Refrain
 - Debt contract by date @ £150.00 p/h + price set by Miss Refrain
 - Masked fetish modelling @ £150.00 p/h
 - Phone sex @ £150.00 p/h
 - Masked camming @ £150.00 p/h
relative_permalinks: false
